from enum import Enum


class LayerType(str, Enum):
    LINEAR = "Linear"
    ATTENTION = "Attention"
    ATTENTION_QKV = "AttentionQKVLinear"
    ATTENTION_PROJ = "AttentionProjection"
    ATTENTION_MASK = "AttentionMask"
    BIAS = "Bias"
    EMBEDDING = "Embedding"
    POSITIONAL_EMBEDDING = "PositionalEmbedding"
    LAYERNORM = "LayerNorm"
    LAYERNORM_FINAL = "LayerNormFinal"
    RMSNORM = "RMSNorm"
    BATCHNORM = "BatchNorm"
    GROUPNORM = "GroupNorm"
    INSTANCENORM = "InstanceNorm"
    MULTIHEAD_ATTENTION = "MultiheadAttention"
    SELF_ATTENTION = "SelfAttention"
    CROSS_ATTENTION = "CrossAttention"
    CONV1D = "Conv1D"
    CONV2D = "Conv2D"
    CONV3D = "Conv3D"
    DEPTHWISE_CONV = "DepthwiseConv"
    CONV = "Conv"
    CLASSIFIER = "Classifier"
    CLASSIFIER_FINAL = "ClassifierFinal"
    SCALING = "Scaling"
    POOLING = "Pooling"
    UNKNOWN = "Unknown"
